### ISSUE TITLE
This makes illegal use of my intelectual property. 

### ISSUE THREAD

**Issue by slipster216** [OCB7D2D/OcbMicroSplat#1]
MicroSplat is not open source, and you are illegally including it's source in this repository.

**Comment by mgreter** [comment]
Please see https://github.com/OCB7D2D/OcbMicroSplat/blob/master/Unity/MicroSplatShader/Assets/OcbMicroSplat/Includes/README.md
Most parts are from the freely available bundle. But as stated, if you are the copyright holder and insist, I'll remove it.

**Comment by slipster216** [comment]
It doesn't matter if it's free (and it also includes parts of paid modules), it's still a violation of my copywrite to distribute it without permission.

**Comment by mgreter** [comment]
I've removed the parts and I apologize for not doing everything 100% by the book. It was not my intention to "pirate" anything and I always told everyone, in case they want to work with the code themselves, that they need to get the proper licenses from unity store (as I also did). Hope that resolves the issue and sorry again. Still wish you a good 2024 and keep up the good work.
